### ISSUE TITLE
Align and update Development Themes vocabulary

### ISSUE THREAD

**Issue by kaerumy** [Sinar/sinarngo#34]
Current set is here:
https://github.com/Sinar/sinar.miscbehavior/blob/main/src/sinar/miscbehavior/vocabularies/development_themes.py

Cluster intersectional
![image](https://github.com/Sinar/sinarngo/assets/1060743/a047ada1-e7f3-4b43-8bf7-861418d0c116)

To discuss an updated list with MEL group

**Comment by samqi** [comment]
where is this used?

**Comment by samqi** [comment]
as discussed in this weeks standup - recommended to standardise to about 8 would be sufficient

**Comment by kaerumy** [comment]
Also ensure that the 8 themes, will cover all 18 SDGs eg. Environment will cover SDG 13,14,15.  

- Broad themes (this list of 8-10)
- SDGs a bit more detailed including detailed SDGs eg. 16.10
- More thematic specific breakdowns, this are probably best left as tags or something that is tracked by the orgs working on these specialized themes, but we can accommodate upon request.

**Comment by samqi** [comment]
![image](https://github.com/Sinar/sinarngo/assets/14970534/32d799ef-62da-40cc-8f7d-8fae4b1727c3)

If you want to use your cluster intersectional themes as baseline then:

1. Environment (& Agriculture?)
2. Youth & Child Rights
3. Women & Gender
4. Culture of Policing, Punishment
5. Economy, Labour Rights, Migrants & Refugees
6. Human Rights  (including Education, Health, Older persons, Religious Affairs)
7. Disability
8. Indigineous Peoples & Affairs

cross ref with:
- [SDG Goals](https://iatistandard.org/en/iati-standard/203/codelists/unsdg-goals/)
- [SDG Targets](https://iatistandard.org/en/iati-standard/203/codelists/unsdg-targets/)

**Comment by samqi** [comment]
- Accountability and Transparency
- Agriculture
- Child Rights
- Crime
- Environment
- Economy
- Education
- Energy
- Health
- Human Rights
- Indigenous Affairs
- Labour Rights
- Migrants & Refugees
- Legislative Assemblies and Parliament
- Procurement and Contracts
- Religious Affairs
- Water and Sanitation
- Women and Gender
- Accessibility
- Transportation
- Infrastructure

last discussed, we concluded with this. Closing this issue with the above concluded. 

@kaerumy , you can reopen issue if there are any more additional input or felt this issue reached incomplete conclusion or require further clarification with the cluster.
